import type { Title } from "@/modules/catalog";

const THUMB = (seed: string) => `https://picsum.photos/seed/${seed}/400/600`;
const BACKDROP = (seed: string) => `https://picsum.photos/seed/${seed}/1280/720`;

const STREAMS = {
  muxStandard: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
  appleBipBop:
    "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8",
  tearsOfSteel: "https://test-streams.mux.dev/tos_ismc/main.m3u8",
  bigBuckBunny: "https://test-streams.mux.dev/pts_shift/master.m3u8",
} as const;

export const CATALOG: readonly Title[] = [
  {
    id: "aurora-protocol",
    title: "Aurora Protocol",
    synopsis:
      "A rogue AI satellite goes dark over the Arctic, and the only engineer who can reach it has 12 hours before it falls.",
    category: "Sci-Fi",
    year: 2023,
    rating: "PG-13",
    score: 8.1,
    durationMinutes: 124,
    thumbnailUrl: THUMB("aurora"),
    backdropUrl: BACKDROP("aurora"),
    streamUrl: STREAMS.muxStandard,
  },
  {
    id: "midnight-diner",
    title: "Midnight Diner",
    synopsis:
      "Regulars at a 24-hour diner trade secrets, grudges, and the occasional confession over bottomless coffee.",
    category: "Drama",
    year: 2021,
    rating: "TV-MA",
    score: 7.6,
    durationMinutes: 98,
    thumbnailUrl: THUMB("diner"),
    backdropUrl: BACKDROP("diner"),
    streamUrl: STREAMS.tearsOfSteel,
  },
  {
    id: "paper-tigers",
    title: "Paper Tigers",
    synopsis:
      "Three aging martial-arts students reunite to avenge their master, only to discover they have forgotten almost everything.",
    category: "Action",
    year: 2020,
    rating: "PG-13",
    score: 6.9,
    durationMinutes: 110,
    thumbnailUrl: THUMB("tigers"),
    backdropUrl: BACKDROP("tigers"),
    streamUrl: STREAMS.appleBipBop,
  },
  {
    id: "the-quiet-coast",
    title: "The Quiet Coast",
    synopsis:
      "A nature documentary following a year in the life of a fragile shoreline and the people fighting to protect it.",
    category: "Documentary",
    year: 2022,
    rating: "TV-G",
    score: 8.4,
    durationMinutes: 87,
    thumbnailUrl: THUMB("coast"),
    backdropUrl: BACKDROP("coast"),
    streamUrl: STREAMS.bigBuckBunny,
  },
  {
    id: "office-hours",
    title: "Office Hours",
    synopsis:
      "A burnt-out professor and an over-eager TA accidentally launch the most popular podcast on campus.",
    category: "Comedy",
    year: 2024,
    rating: "TV-14",
    score: 7.2,
    durationMinutes: 102,
    thumbnailUrl: THUMB("office"),
    backdropUrl: BACKDROP("office"),
    streamUrl: STREAMS.muxStandard,
  },
  {
    id: "starlight-runners",
    title: "Starlight Runners",
    synopsis:
      "In a neon megacity, two courier kids stumble onto a package that half the planet wants to bury.",
    category: "Animation",
    year: 2023,
    rating: "PG",
    score: 8.0,
    durationMinutes: 95,
    thumbnailUrl: THUMB("starlight"),
    backdropUrl: BACKDROP("starlight"),
    streamUrl: STREAMS.tearsOfSteel,
  },
  {
    id: "ironwood",
    title: "Ironwood",
    synopsis:
      "A frontier blacksmith turned reluctant sheriff must hold a collapsing town together for one long winter.",
    category: "Drama",
    year: 2019,
    rating: "TV-MA",
    score: 7.9,
    durationMinutes: 131,
    thumbnailUrl: THUMB("ironwood"),
    backdropUrl: BACKDROP("ironwood"),
    streamUrl: STREAMS.appleBipBop,
  },
  {
    id: "deep-field",
    title: "Deep Field",
    synopsis:
      "A look inside the teams chasing the faintest light in the universe, and what it tells us about where we came from.",
    category: "Documentary",
    year: 2023,
    rating: "TV-PG",
    score: 8.7,
    durationMinutes: 76,
    thumbnailUrl: THUMB("deepfield"),
    backdropUrl: BACKDROP("deepfield"),
    streamUrl: STREAMS.bigBuckBunny,
  },
  {
    id: "crash-cart",
    title: "Crash Cart",
    synopsis:
      "The night shift of an understaffed ER, where every shift is a sprint and nobody goes home unchanged.",
    category: "Drama",
    year: 2022,
    rating: "TV-MA",
    score: 7.4,
    durationMinutes: 105,
    thumbnailUrl: THUMB("crashcart"),
    backdropUrl: BACKDROP("crashcart"),
    streamUrl: STREAMS.muxStandard,
  },
  {
    id: "neon-heist",
    title: "Neon Heist",
    synopsis:
      "A retired thief is pulled back for one last job: robbing the bank that ruined her, on the night of its grand reopening.",
    category: "Action",
    year: 2024,
    rating: "R",
    score: 7.0,
    durationMinutes: 118,
    thumbnailUrl: THUMB("neonheist"),
    backdropUrl: BACKDROP("neonheist"),
    streamUrl: STREAMS.tearsOfSteel,
  },
  {
    id: "the-understudy",
    title: "The Understudy",
    synopsis:
      "A nervous understudy gets one shot at the lead role — the same night a critic who hates the director shows up.",
    category: "Comedy",
    year: 2021,
    rating: "PG-13",
    score: 6.8,
    durationMinutes: 92,
    thumbnailUrl: THUMB("understudy"),
    backdropUrl: BACKDROP("understudy"),
    streamUrl: STREAMS.appleBipBop,
  },
  {
    id: "orbital",
    title: "Orbital",
    synopsis:
      "Six strangers aboard a failing space station have one orbit — 90 minutes — to fix what's broken or burn up on reentry.",
    category: "Sci-Fi",
    year: 2022,
    rating: "PG-13",
    score: 8.3,
    durationMinutes: 108,
    thumbnailUrl: THUMB("orbital"),
    backdropUrl: BACKDROP("orbital"),
    streamUrl: STREAMS.bigBuckBunny,
  },
  {
    id: "glass-harbor",
    title: "Glass Harbor",
    synopsis:
      "A grieving architect returns to the seaside town she left at eighteen and finds the past has been waiting for her.",
    category: "Drama",
    year: 2020,
    rating: "TV-14",
    score: 7.5,
    durationMinutes: 116,
    thumbnailUrl: THUMB("glassharbor"),
    backdropUrl: BACKDROP("glassharbor"),
    streamUrl: STREAMS.tearsOfSteel,
  },
  {
    id: "pixel-pals",
    title: "Pixel Pals",
    synopsis:
      "Two glitchy arcade sprites escape their cabinet and discover the chaotic, wonderful world of the back room.",
    category: "Animation",
    year: 2024,
    rating: "G",
    score: 7.8,
    durationMinutes: 84,
    thumbnailUrl: THUMB("pixelpals"),
    backdropUrl: BACKDROP("pixelpals"),
    streamUrl: STREAMS.bigBuckBunny,
  },
  {
    id: "the-last-laugh",
    title: "The Last Laugh",
    synopsis:
      "An aging comedian and his estranged daughter drive cross-country to one final, disastrous, unforgettable gig.",
    category: "Comedy",
    year: 2023,
    rating: "R",
    score: 7.1,
    durationMinutes: 99,
    thumbnailUrl: THUMB("lastlaugh"),
    backdropUrl: BACKDROP("lastlaugh"),
    streamUrl: STREAMS.muxStandard,
  },
  {
    id: "blackout-mile",
    title: "Blackout Mile",
    synopsis:
      "When the grid fails for a single city block, neighbours discover what they're capable of in the dark.",
    category: "Action",
    year: 2022,
    rating: "TV-MA",
    score: 6.6,
    durationMinutes: 101,
    thumbnailUrl: THUMB("blackoutmile"),
    backdropUrl: BACKDROP("blackoutmile"),
    streamUrl: STREAMS.appleBipBop,
  },
  {
    id: "the-reef",
    title: "The Reef",
    synopsis:
      "A decade-long study of a single coral reef, and the scientists racing to save it before the next warm season.",
    category: "Documentary",
    year: 2021,
    rating: "TV-G",
    score: 8.5,
    durationMinutes: 79,
    thumbnailUrl: THUMB("thereef"),
    backdropUrl: BACKDROP("thereef"),
    streamUrl: STREAMS.tearsOfSteel,
  },
  {
    id: "vector-prime",
    title: "Vector Prime",
    synopsis:
      "A quantum courier must deliver a message that exists in two places at once before either copy is erased.",
    category: "Sci-Fi",
    year: 2024,
    rating: "PG-13",
    score: 7.7,
    durationMinutes: 122,
    thumbnailUrl: THUMB("vectorprime"),
    backdropUrl: BACKDROP("vectorprime"),
    streamUrl: STREAMS.muxStandard,
  },
  {
    id: "second-chair",
    title: "Second Chair",
    synopsis:
      "A junior public defender takes on the case nobody wants and learns the law is the easy part.",
    category: "Drama",
    year: 2023,
    rating: "TV-14",
    score: 8.0,
    durationMinutes: 113,
    thumbnailUrl: THUMB("secondchair"),
    backdropUrl: BACKDROP("secondchair"),
    streamUrl: STREAMS.bigBuckBunny,
  },
  {
    id: "moonlit-bakery",
    title: "Moonlit Bakery",
    synopsis:
      "A hand-drawn tale of a tiny night bakery whose bread grants its eaters one small, perfect dream.",
    category: "Animation",
    year: 2022,
    rating: "G",
    score: 8.2,
    durationMinutes: 88,
    thumbnailUrl: THUMB("moonlitbakery"),
    backdropUrl: BACKDROP("moonlitbakery"),
    streamUrl: STREAMS.appleBipBop,
  },
];